@startuml
class PoolWarmer {
    + PoolWarmer(prefabPool:IPrefabPool, poolWarmupConfig:PoolWarmupConfig)
    + Initialize() : void
}
IInitializable <|-- PoolWarmer
PoolWarmer --> "_poolWarmupConfig" PoolWarmupConfig
PoolWarmer --> "_prefabPool" IPrefabPool
@enduml
