@startuml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Camera\CameraControl.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\Elf.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\ElfColor.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\ElfController.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\ElfData.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\ElfMovementBehavior.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\ElfView.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Collision\CollisionDecision.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Collision\ElfCollisionHandler.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Pooling\AutoReturnToPool.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Pooling\PoolWarmer.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Pooling\PoolWarmupEntry.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Pooling\PrefabPool.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Services\ElfSpawnCooldownService.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Services\SpawnRequestService.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Services\VFXService.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\DeadState.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\ElfBaseState.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\ElfStateManager.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\IElfState.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\NormalState.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\StunnedState.puml
@enduml
