@startuml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Camera\CameraControl.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\Elf.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\ElfColor.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\ElfController.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\ElfData.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\ElfMovementBehavior.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\NavMeshAgentWrapper.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Pooling\AutoReturnToPool.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Pooling\IPrefabPool.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Pooling\PoolWarmer.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Pooling\PoolWarmupEntry.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Pooling\PrefabPool.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Pooling\ZenjectInstantiator.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Services\VFXService.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Spawners\ISpawner.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Spawners\Spawner.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Spawners\SpawnerData.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Spawners\SpawnerFactory.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\Collision\CollisionDecision.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\Collision\ColorBasedCollisionStrategy.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\Collision\ElfCollisionHandler.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\Services\SpawnGlobalCooldownService.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\DeadState.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\ElfBaseState.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\ElfStateManager.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\IElfState.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\NormalState.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\States\StunnedState.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Characters\View\ElfView.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Spawners\Services\SpawnerRegistryService.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Spawners\Services\SpawnRequestService.puml
!include .\\.\Assets\ExplodingElves\Scripts\Core\Spawners\Views\SpawnerView.puml
@enduml
